-- MySQL Script generated by MySQL Workbench
-- Sun Mar 29 23:58:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_dfrp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_dfrp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_dfrp` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci ;
USE `db_dfrp` ;

-- -----------------------------------------------------
-- Table `db_dfrp`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`accounts` (
  `accid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `level` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `xp` INT UNSIGNED NOT NULL DEFAULT 0,
  `pass` VARCHAR(256) NOT NULL,
  `admin` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `idv` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `invited` INT UNSIGNED NOT NULL DEFAULT 0,
  `mp` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `ip` VARCHAR(15) NOT NULL DEFAULT '000.000.000.000',
  `registerdate` INT UNSIGNED NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `whitelist` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`accid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`characters` (
  `charid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `accid` INT UNSIGNED NOT NULL,
  `orgid` INT UNSIGNED NOT NULL DEFAULT 0,
  `paymentid` INT UNSIGNED NOT NULL DEFAULT 0,
  `state` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(20) NOT NULL,
  `lastname` VARCHAR(20) NOT NULL,
  `skinid` SMALLINT NOT NULL,
  `bornin` INT UNSIGNED NOT NULL,
  `money` INT NOT NULL,
  `X` FLOAT NOT NULL,
  `Y` FLOAT NOT NULL,
  `Z` FLOAT NOT NULL,
  `A` FLOAT NOT NULL,
  `interior` SMALLINT UNSIGNED NOT NULL,
  `vworld` SMALLINT UNSIGNED NOT NULL,
  `driver` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `prision` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`charid`),
  INDEX `fk_characters_accounts_idx` (`accid` ASC),
  CONSTRAINT `fk_accid`
    FOREIGN KEY (`accid`)
    REFERENCES `db_dfrp`.`accounts` (`accid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `db_dfrp`.`business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`business` (
  `businessid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ownerid` INT UNSIGNED NOT NULL DEFAULT 0,
  `bankaccid` INT UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(64) NOT NULL,
  `value` INT NOT NULL DEFAULT 0,
  `type` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `cash` INT NOT NULL DEFAULT 0,
  `X` FLOAT NOT NULL DEFAULT 0.0,
  `Y` FLOAT NOT NULL DEFAULT 0.0,
  `Z` FLOAT NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`businessid`),
  INDEX `fk_charid_idx` (`ownerid` ASC),
  CONSTRAINT `fk_charid`
    FOREIGN KEY (`ownerid`)
    REFERENCES `db_dfrp`.`characters` (`charid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`busroutes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`busroutes` (
  `busrouteid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `businessid` INT UNSIGNED NOT NULL,
  `value` INT UNSIGNED NOT NULL DEFAULT 0,
  `numstops` TINYINT UNSIGNED NOT NULL,
  `s0` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s1` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s2` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s3` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s4` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s5` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s6` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s7` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s8` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s9` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s10` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s11` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s12` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s13` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s14` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s15` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s16` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s17` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s18` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `s19` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`busrouteid`),
  INDEX `fk_businessid_idx` (`businessid` ASC),
  CONSTRAINT `fk_businessid`
    FOREIGN KEY (`businessid`)
    REFERENCES `db_dfrp`.`business` (`businessid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`charges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`charges` (
  `chargeid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `businessid` INT UNSIGNED NOT NULL,
  `charid` INT UNSIGNED NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `salary` INT UNSIGNED NOT NULL DEFAULT 0,
  `permission` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `receive` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`chargeid`),
  INDEX `fk_charid_idx` (`charid` ASC),
  INDEX `fk_businessid_idx` (`businessid` ASC),
  CONSTRAINT `fk_charid`
    FOREIGN KEY (`charid`)
    REFERENCES `db_dfrp`.`characters` (`charid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_businessid`
    FOREIGN KEY (`businessid`)
    REFERENCES `db_dfrp`.`business` (`businessid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`bankaccounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`bankaccounts` (
  `bankaccid` INT UNSIGNED NOT NULL,
  `sold` INT NOT NULL DEFAULT 0,
  `name` VARCHAR(64) NOT NULL,
  `pass` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`bankaccid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`files` (
  `fileid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `value` MEDIUMINT UNSIGNED NOT NULL,
  `gasoline` MEDIUMINT NOT NULL,
  `destiny` TINYINT NOT NULL,
  PRIMARY KEY (`fileid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`houses` (
  `houseid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ownerid` INT UNSIGNED NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `neighbourhood` INT UNSIGNED NOT NULL,
  `number` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`houseid`),
  INDEX `fk_ownerid_idx` (`ownerid` ASC),
  CONSTRAINT `fk_ownerid`
    FOREIGN KEY (`ownerid`)
    REFERENCES `db_dfrp`.`characters` (`charid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`doors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`doors` (
  `doorid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `enterX` FLOAT NOT NULL,
  `enterY` FLOAT NOT NULL,
  `enterZ` FLOAT NOT NULL,
  `enterA` FLOAT NOT NULL,
  `enterInt` TINYINT UNSIGNED NOT NULL,
  `enterVW` SMALLINT UNSIGNED NOT NULL,
  `exitX` FLOAT NOT NULL,
  `exitY` FLOAT NOT NULL,
  `exitZ` FLOAT NOT NULL,
  `exitA` FLOAT NOT NULL,
  `exitInt` TINYINT UNSIGNED NOT NULL,
  `exitVW` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`doorid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`doorkeys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`doorkeys` (
  `doorkeyid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `doorid` INT UNSIGNED NOT NULL,
  `charid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`doorkeyid`),
  INDEX `fk_doorid_idx` (`doorid` ASC),
  INDEX `fk_charid_idx` (`charid` ASC),
  CONSTRAINT `fk_doorid`
    FOREIGN KEY (`doorid`)
    REFERENCES `db_dfrp`.`doors` (`doorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_charid`
    FOREIGN KEY (`charid`)
    REFERENCES `db_dfrp`.`characters` (`charid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`kickbans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`kickbans` (
  `kickbanid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userid` INT UNSIGNED NOT NULL,
  `adminid` INT UNSIGNED NOT NULL,
  `ipadress` VARCHAR(15) NOT NULL DEFAULT '000.000.000.000',
  `punishment` INT UNSIGNED NOT NULL DEFAULT 0,
  `timestamp` INT UNSIGNED NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `motive` VARCHAR(64) NOT NULL DEFAULT 'N/A',
  PRIMARY KEY (`kickbanid`),
  INDEX `fk_userid_idx` (`userid` ASC),
  INDEX `fk_adminid_idx` (`adminid` ASC),
  CONSTRAINT `fk_userid`
    FOREIGN KEY (`userid`)
    REFERENCES `db_dfrp`.`accounts` (`accid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adminid`
    FOREIGN KEY (`adminid`)
    REFERENCES `db_dfrp`.`accounts` (`accid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`orgs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`orgs` (
  `orgid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ownerid` INT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL DEFAULT 'N/A',
  PRIMARY KEY (`orgid`),
  INDEX `fk_ownerid_idx` (`ownerid` ASC),
  CONSTRAINT `fk_ownerid`
    FOREIGN KEY (`ownerid`)
    REFERENCES `db_dfrp`.`characters` (`charid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`members` (
  `memberid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orgid` INT UNSIGNED NOT NULL,
  `charid` INT UNSIGNED NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `permission` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`memberid`),
  INDEX `fk_charid_idx` (`charid` ASC),
  INDEX `fk_orgid_idx` (`orgid` ASC),
  CONSTRAINT `fk_charid`
    FOREIGN KEY (`charid`)
    REFERENCES `db_dfrp`.`characters` (`charid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orgid`
    FOREIGN KEY (`orgid`)
    REFERENCES `db_dfrp`.`orgs` (`orgid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`products` (
  `prodid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `businessid` INT UNSIGNED NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `amount` INT NOT NULL DEFAULT 0,
  `price` FLOAT NOT NULL,
  `model` INT NOT NULL,
  PRIMARY KEY (`prodid`),
  INDEX `fk_businessid_idx` (`businessid` ASC),
  CONSTRAINT `fk_businessid`
    FOREIGN KEY (`businessid`)
    REFERENCES `db_dfrp`.`business` (`businessid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`servertime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`servertime` (
  `timestamp` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`teleport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`teleport` (
  `tpid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `x` FLOAT NOT NULL,
  `y` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `a` FLOAT NOT NULL,
  `interior` SMALLINT NOT NULL,
  `vworld` SMALLINT NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`tpid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`vehparams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`vehparams` (
  `modelid` SMALLINT UNSIGNED NOT NULL,
  `gasCapacity` FLOAT NOT NULL,
  `gasSpent` FLOAT NOT NULL,
  `bootDistance` FLOAT NOT NULL,
  PRIMARY KEY (`modelid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`vehicles` (
  `vehid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ownerid` INT UNSIGNED NOT NULL,
  `modelid` SMALLINT UNSIGNED NOT NULL,
  `color1` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `color2` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `x` FLOAT NOT NULL,
  `y` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `a` FLOAT NOT NULL,
  `gas` FLOAT NOT NULL DEFAULT 0.0,
  `gps` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`vehid`),
  INDEX `fk_ownerid_idx` (`ownerid` ASC),
  INDEX `fk_modelid_idx` (`modelid` ASC),
  CONSTRAINT `fk_ownerid`
    FOREIGN KEY (`ownerid`)
    REFERENCES `db_dfrp`.`characters` (`charid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelid`
    FOREIGN KEY (`modelid`)
    REFERENCES `db_dfrp`.`vehparams` (`modelid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`vehiclekeys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`vehiclekeys` (
  `vehkeyid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vehid` INT UNSIGNED NOT NULL,
  `charid` INT UNSIGNED NOT NULL,
  `locationid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`vehkeyid`),
  INDEX `fk_vehid_idx` (`vehid` ASC),
  INDEX `fk_charid_idx` (`charid` ASC),
  CONSTRAINT `fk_vehid`
    FOREIGN KEY (`vehid`)
    REFERENCES `db_dfrp`.`vehicles` (`vehid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_charid`
    FOREIGN KEY (`charid`)
    REFERENCES `db_dfrp`.`characters` (`charid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dfrp`.`vstaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dfrp`.`vstaff` (
  `vstaffid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `charid` INT UNSIGNED NOT NULL,
  `modelid` INT UNSIGNED NOT NULL DEFAULT 400,
  `color1` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `color2` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `x` FLOAT NOT NULL,
  `y` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `a` FLOAT NOT NULL,
  `interior` SMALLINT UNSIGNED NOT NULL,
  `vworld` SMALLINT UNSIGNED NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`vstaffid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
